[build]
  command = "echo 'Function build complete'"

[build.environment]
  # Disable secrets scanning for expected configuration files and documentation
  SECRETS_SCAN_OMIT_PATHS = "metrics/**,*.md,templates/**,netlify.toml,.env"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true