[build]
  publish = "static"
  command = "echo 'Static build complete'"

[build.environment]
  # Disable secrets scanning for expected configuration files and documentation
  SECRETS_SCAN_OMIT_PATHS = "metrics/**,*.md,templates/**,netlify.toml,.env"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/.netlify/functions/app/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200